// Per-plugin UI-chrome i18n catalogs of the first-party plugins. Keyed by plugin
// slug → language → `plugin.<slug>.*` id → text. Attached to each manifest's
// `messages` in manifests.ts; the engine resolves them through `ctx.t`, the
// editor registers them under the `plugin:<id>` namespace. English is the
// fallback base. Hand-maintained (the batch-B codemod generated the first cut).

export const PLUGIN_MESSAGES: Record<string, Partial<Record<string, Record<string, string>>>> = {
  "abreplay": {
    en: {"plugin.abreplay.desc":"A–B story replays: mark a start and an end node as a segment in the Replays panel; players unlock it in the game menu's gallery by passing its end in normal play. When off, segments neither register nor unlock.","plugin.abreplay.name":"Story replays","plugin.abreplay.panel":"Replays","plugin.abreplay.panel.add":"＋ New replay segment","plugin.abreplay.panel.end":"B·to","plugin.abreplay.panel.intro":"A–B replay segments: each records a start and an end node (position ids). Players unlock a segment in the game's 回想 gallery by reaching its end in normal play. Pick an end node the story actually passes through (dialogue/command — not a choice or jump).","plugin.abreplay.panel.needsNodes":"The current scene has no nodes yet — add some story first","plugin.abreplay.panel.start":"A·from","plugin.abreplay.panel.title":"Segment title (shown in the gallery)"},
    zh: {"plugin.abreplay.desc":"A-B 剧情回放：在「回放」面板圈选起止两个节点成一段；玩家正常剧情经过终点后，游戏菜单的「回想」画廊里解锁重看。关闭后段落不再注册、不再解锁。","plugin.abreplay.name":"剧情回放","plugin.abreplay.panel":"回放","plugin.abreplay.panel.add":"＋ 新建回放段","plugin.abreplay.panel.end":"B·终","plugin.abreplay.panel.intro":"A-B 回放段：每段记录起点和终点两个节点（位置ID）。玩家在正常剧情中经过终点后，游戏菜单的「回想」里就会解锁这一段。终点请选剧情真正会经过的节点（对白/指令，不要选选项或跳转）。","plugin.abreplay.panel.needsNodes":"当前场景还没有内容，先加几句剧情吧","plugin.abreplay.panel.start":"A·起","plugin.abreplay.panel.title":"回放段标题（显示在回想画廊）"},
    ja: {"plugin.abreplay.desc":"A–B シーン回想：「リプレイ」パネルで開始・終了ノードを選んで区間を作成。プレイヤーが本編で終点を通過すると、ゲームメニューの「回想」で解放されます。オフにすると区間は登録・解放されません。","plugin.abreplay.name":"シーン回想","plugin.abreplay.panel":"リプレイ","plugin.abreplay.panel.add":"＋ リプレイ区間を作成","plugin.abreplay.panel.end":"B·終","plugin.abreplay.panel.intro":"A–B リプレイ区間：各区間は開始と終了の 2 ノード（位置ID）を記録します。プレイヤーが本編で終点を通過すると、ゲームメニューの「回想」でその区間が解放されます。終点には物語が実際に通過するノード（セリフ／コマンド）を選んでください（選択肢やジャンプは不可）。","plugin.abreplay.panel.needsNodes":"現在のシーンにはまだ内容がありません。先に物語を追加してください","plugin.abreplay.panel.start":"A·始","plugin.abreplay.panel.title":"区間タイトル（回想ギャラリーに表示）"},
  },
  "animstudio": {
    en: {"plugin.animstudio.desc":"Keyframe animation: plays back timeline-recorded multi-object choreography (camera included), background loops and one-object clips. When off, these animations no longer play — authored data stays and previews still run.","plugin.animstudio.name":"Animation studio"},
    zh: {"plugin.animstudio.desc":"关键帧动画：播放时间轴录制的多对象编排（含镜头）、背景循环动画和单对象动画片段。关闭后这些动画不再播放——作品数据保留，预览照常运行。","plugin.animstudio.name":"动画工坊"},
    ja: {"plugin.animstudio.desc":"キーフレームアニメ：タイムラインで録画した複数オブジェクトの演出（カメラ含む）、背景ループ、単一オブジェクトのクリップを再生します。オフにすると再生されません——データは保持され、プレビューは通常どおり動作します。","plugin.animstudio.name":"アニメスタジオ"},
  },
  "charfx": {
    en: {"plugin.charfx.cmd.charfx.duration":"Duration (s)","plugin.charfx.cmd.charfx.hint":"Make the sprite hop / nod / wobble / swing","plugin.charfx.cmd.charfx.id":"Character","plugin.charfx.cmd.charfx.label":"Character motion","plugin.charfx.cmd.charfx.preset":"Action","plugin.charfx.cmd.charfx.preset.hop":"Hop","plugin.charfx.cmd.charfx.preset.nod":"Nod","plugin.charfx.cmd.charfx.preset.shake":"Wobble","plugin.charfx.cmd.charfx.preset.swing":"Swing","plugin.charfx.cmd.move.hint":"Move the sprite to left / center / right","plugin.charfx.cmd.move.id":"Character","plugin.charfx.cmd.move.label":"Move sprite","plugin.charfx.cmd.move.time":"Duration (s)","plugin.charfx.cmd.move.to":"Move to","plugin.charfx.cmd.move.to.center":"Center","plugin.charfx.cmd.move.to.left":"Left","plugin.charfx.cmd.move.to.right":"Right","plugin.charfx.desc":"Character motion: hop / nod / shake / swing, plus moving the sprite left and right. When off, these motion commands have no effect.","plugin.charfx.fx.pose.label":"Character motion","plugin.charfx.name":"Character motion"},
    zh: {"plugin.charfx.cmd.charfx.duration":"时长(秒)","plugin.charfx.cmd.charfx.hint":"让立绘跳一下 / 点头 / 摇晃 / 摆动","plugin.charfx.cmd.charfx.id":"角色","plugin.charfx.cmd.charfx.label":"角色动作","plugin.charfx.cmd.charfx.preset":"动作","plugin.charfx.cmd.charfx.preset.hop":"跳一下","plugin.charfx.cmd.charfx.preset.nod":"点头","plugin.charfx.cmd.charfx.preset.shake":"摇晃","plugin.charfx.cmd.charfx.preset.swing":"摆动","plugin.charfx.cmd.move.hint":"把立绘移到左 / 中 / 右","plugin.charfx.cmd.move.id":"角色","plugin.charfx.cmd.move.label":"移动立绘","plugin.charfx.cmd.move.time":"时长(秒)","plugin.charfx.cmd.move.to":"移到","plugin.charfx.cmd.move.to.center":"中","plugin.charfx.cmd.move.to.left":"左","plugin.charfx.cmd.move.to.right":"右","plugin.charfx.desc":"角色动作：跳一下 / 点头 / 摇晃 / 摆动，以及左右移动立绘。关闭后相关动作指令不再生效。","plugin.charfx.fx.pose.label":"角色动作","plugin.charfx.name":"角色动作"},
    ja: {"plugin.charfx.cmd.charfx.duration":"長さ(秒)","plugin.charfx.cmd.charfx.hint":"立ち絵をジャンプ／うなずき／揺れ／スイングさせる","plugin.charfx.cmd.charfx.id":"キャラクター","plugin.charfx.cmd.charfx.label":"キャラクター動作","plugin.charfx.cmd.charfx.preset":"アクション","plugin.charfx.cmd.charfx.preset.hop":"ジャンプ","plugin.charfx.cmd.charfx.preset.nod":"うなずき","plugin.charfx.cmd.charfx.preset.shake":"揺れ","plugin.charfx.cmd.charfx.preset.swing":"スイング","plugin.charfx.cmd.move.hint":"立ち絵を左／中／右へ移動","plugin.charfx.cmd.move.id":"キャラクター","plugin.charfx.cmd.move.label":"立ち絵を移動","plugin.charfx.cmd.move.time":"長さ(秒)","plugin.charfx.cmd.move.to":"移動先","plugin.charfx.cmd.move.to.center":"中央","plugin.charfx.cmd.move.to.left":"左","plugin.charfx.cmd.move.to.right":"右","plugin.charfx.desc":"キャラクター動作：ジャンプ／うなずき／揺れ／スイング、および立ち絵の左右移動。オフにすると関連する動作コマンドは無効になります。","plugin.charfx.fx.pose.label":"キャラクター動作","plugin.charfx.name":"キャラクター動作"},
  },
  "choicefx": {
    en: {"plugin.choicefx.desc":"Choice effects: branch buttons slide in one by one with a hover sheen. Purely decorative; when off, choices appear immediately.","plugin.choicefx.name":"Choice effects"},
    zh: {"plugin.choicefx.desc":"选项动效：分支按钮逐个滑入 + 悬停反光。纯装饰，关闭后选项直接显示。","plugin.choicefx.name":"选项动效"},
    ja: {"plugin.choicefx.desc":"選択肢の演出：分岐ボタンが一つずつスライドイン＋ホバー時の光沢。装飾のみで、オフにすると選択肢はそのまま表示されます。","plugin.choicefx.name":"選択肢の演出"},
  },
  "objectfx": {
    en: {"plugin.objectfx.cmd.fade.dir":"Direction","plugin.objectfx.cmd.fade.dir.in":"Fade in","plugin.objectfx.cmd.fade.dir.out":"Fade out","plugin.objectfx.cmd.fade.duration":"Duration (s)","plugin.objectfx.cmd.fade.hint":"Fade an object in or out","plugin.objectfx.cmd.fade.kind":"Object kind","plugin.objectfx.cmd.fade.label":"Fade","plugin.objectfx.cmd.fade.target":"Target (screen = camera, or an object id)","plugin.objectfx.cmd.layer.hint":"Move the object in front of the dialogue box, or back onto the stage","plugin.objectfx.cmd.layer.kind":"Object kind","plugin.objectfx.cmd.layer.label":"Layer","plugin.objectfx.cmd.layer.layer":"Position","plugin.objectfx.cmd.layer.layer.front":"In front of dialogue","plugin.objectfx.cmd.layer.layer.world":"Back to stage","plugin.objectfx.cmd.layer.target":"Target (screen = camera, or an object id)","plugin.objectfx.cmd.opacity.duration":"Duration (s)","plugin.objectfx.cmd.opacity.hint":"Set an object's opacity to a given value (0–1)","plugin.objectfx.cmd.opacity.kind":"Object kind","plugin.objectfx.cmd.opacity.label":"Opacity","plugin.objectfx.cmd.opacity.target":"Target (screen = camera, or an object id)","plugin.objectfx.cmd.opacity.to":"Opacity (0–1)","plugin.objectfx.cmd.scale.duration":"Duration (s)","plugin.objectfx.cmd.scale.hint":"Scale an object to a given factor (camera = zoom)","plugin.objectfx.cmd.scale.kind":"Object kind","plugin.objectfx.cmd.scale.label":"Scale","plugin.objectfx.cmd.scale.target":"Target (screen = camera, or an object id)","plugin.objectfx.cmd.scale.to":"Target factor","plugin.objectfx.cmd.visibility.hint":"Hide or show an object (kept on stage, not removed)","plugin.objectfx.cmd.visibility.kind":"Object kind","plugin.objectfx.cmd.visibility.label":"Visibility","plugin.objectfx.cmd.visibility.target":"Target (screen = camera, or an object id)","plugin.objectfx.cmd.visibility.vis":"Visibility","plugin.objectfx.cmd.visibility.vis.hide":"Hide","plugin.objectfx.cmd.visibility.vis.show":"Show","plugin.objectfx.desc":"Object effects: fade, scale, show/hide, and change the opacity of any stage object (character / sprite / camera). When off, these commands have no effect.","plugin.objectfx.fx.fade.label":"Fade","plugin.objectfx.fx.layer.label":"Layer","plugin.objectfx.fx.opacity.label":"Opacity","plugin.objectfx.fx.scale.label":"Scale","plugin.objectfx.fx.visibility.label":"Visibility","plugin.objectfx.name":"Object effects"},
    zh: {"plugin.objectfx.cmd.fade.dir":"方向","plugin.objectfx.cmd.fade.dir.in":"淡入","plugin.objectfx.cmd.fade.dir.out":"淡出","plugin.objectfx.cmd.fade.duration":"时长(秒)","plugin.objectfx.cmd.fade.hint":"让对象淡入或淡出","plugin.objectfx.cmd.fade.kind":"对象类型","plugin.objectfx.cmd.fade.label":"淡入淡出","plugin.objectfx.cmd.fade.target":"对象（screen＝镜头，或对象id）","plugin.objectfx.cmd.layer.hint":"把对象放到对白窗口前，或放回舞台","plugin.objectfx.cmd.layer.kind":"对象类型","plugin.objectfx.cmd.layer.label":"图层","plugin.objectfx.cmd.layer.layer":"位置","plugin.objectfx.cmd.layer.layer.front":"置于对白前","plugin.objectfx.cmd.layer.layer.world":"回到舞台","plugin.objectfx.cmd.layer.target":"对象（screen＝镜头，或对象id）","plugin.objectfx.cmd.opacity.duration":"时长(秒)","plugin.objectfx.cmd.opacity.hint":"把对象透明度设为指定值（0～1）","plugin.objectfx.cmd.opacity.kind":"对象类型","plugin.objectfx.cmd.opacity.label":"改透明度","plugin.objectfx.cmd.opacity.target":"对象（screen＝镜头，或对象id）","plugin.objectfx.cmd.opacity.to":"透明度(0~1)","plugin.objectfx.cmd.scale.duration":"时长(秒)","plugin.objectfx.cmd.scale.hint":"把对象缩放到指定倍数（镜头＝变焦）","plugin.objectfx.cmd.scale.kind":"对象类型","plugin.objectfx.cmd.scale.label":"缩放","plugin.objectfx.cmd.scale.target":"对象（screen＝镜头，或对象id）","plugin.objectfx.cmd.scale.to":"目标倍数","plugin.objectfx.cmd.visibility.hint":"隐藏或显示对象（保留在台，不移除）","plugin.objectfx.cmd.visibility.kind":"对象类型","plugin.objectfx.cmd.visibility.label":"显隐","plugin.objectfx.cmd.visibility.target":"对象（screen＝镜头，或对象id）","plugin.objectfx.cmd.visibility.vis":"可见性","plugin.objectfx.cmd.visibility.vis.hide":"隐藏","plugin.objectfx.cmd.visibility.vis.show":"显示","plugin.objectfx.desc":"对象特效：让任意舞台对象（立绘 / 序列帧 / 镜头）淡入淡出、缩放、显隐、改透明度。关闭后相关指令不再生效。","plugin.objectfx.fx.fade.label":"淡入淡出","plugin.objectfx.fx.layer.label":"图层","plugin.objectfx.fx.opacity.label":"改透明度","plugin.objectfx.fx.scale.label":"缩放","plugin.objectfx.fx.visibility.label":"显隐","plugin.objectfx.name":"对象特效"},
    ja: {"plugin.objectfx.cmd.fade.dir":"方向","plugin.objectfx.cmd.fade.dir.in":"フェードイン","plugin.objectfx.cmd.fade.dir.out":"フェードアウト","plugin.objectfx.cmd.fade.duration":"長さ(秒)","plugin.objectfx.cmd.fade.hint":"オブジェクトをフェードイン / アウト","plugin.objectfx.cmd.fade.kind":"オブジェクト種別","plugin.objectfx.cmd.fade.label":"フェード","plugin.objectfx.cmd.fade.target":"対象（screen＝カメラ、またはオブジェクトid）","plugin.objectfx.cmd.layer.hint":"対象をダイアログの前に出す、または舞台へ戻す","plugin.objectfx.cmd.layer.kind":"オブジェクト種別","plugin.objectfx.cmd.layer.label":"レイヤー","plugin.objectfx.cmd.layer.layer":"位置","plugin.objectfx.cmd.layer.layer.front":"ダイアログの前へ","plugin.objectfx.cmd.layer.layer.world":"舞台へ戻す","plugin.objectfx.cmd.layer.target":"対象（screen＝カメラ、またはオブジェクトid）","plugin.objectfx.cmd.opacity.duration":"長さ(秒)","plugin.objectfx.cmd.opacity.hint":"オブジェクトの不透明度を指定値に（0〜1）","plugin.objectfx.cmd.opacity.kind":"オブジェクト種別","plugin.objectfx.cmd.opacity.label":"不透明度","plugin.objectfx.cmd.opacity.target":"対象（screen＝カメラ、またはオブジェクトid）","plugin.objectfx.cmd.opacity.to":"不透明度(0〜1)","plugin.objectfx.cmd.scale.duration":"長さ(秒)","plugin.objectfx.cmd.scale.hint":"オブジェクトを指定倍率に拡大縮小（カメラ＝ズーム）","plugin.objectfx.cmd.scale.kind":"オブジェクト種別","plugin.objectfx.cmd.scale.label":"拡大縮小","plugin.objectfx.cmd.scale.target":"対象（screen＝カメラ、またはオブジェクトid）","plugin.objectfx.cmd.scale.to":"目標倍率","plugin.objectfx.cmd.visibility.hint":"オブジェクトを表示 / 非表示（舞台に残す）","plugin.objectfx.cmd.visibility.kind":"オブジェクト種別","plugin.objectfx.cmd.visibility.label":"表示切替","plugin.objectfx.cmd.visibility.target":"対象（screen＝カメラ、またはオブジェクトid）","plugin.objectfx.cmd.visibility.vis":"表示","plugin.objectfx.cmd.visibility.vis.hide":"非表示","plugin.objectfx.cmd.visibility.vis.show":"表示","plugin.objectfx.desc":"オブジェクト演出：任意の舞台オブジェクト（立ち絵 / スプライト / カメラ）をフェード・拡大縮小・表示切替・不透明度変更。オフにすると関連コマンドは無効になります。","plugin.objectfx.fx.fade.label":"フェード","plugin.objectfx.fx.layer.label":"レイヤー","plugin.objectfx.fx.opacity.label":"不透明度","plugin.objectfx.fx.scale.label":"拡大縮小","plugin.objectfx.fx.visibility.label":"表示切替","plugin.objectfx.name":"オブジェクト演出"},
  },
  "screenfx": {
    en: {"plugin.screenfx.cmd.flash.color":"Color","plugin.screenfx.cmd.flash.duration":"Duration (s)","plugin.screenfx.cmd.flash.hint":"Flash the whole screen","plugin.screenfx.cmd.flash.label":"Flash","plugin.screenfx.cmd.shake.duration":"Duration (s)","plugin.screenfx.cmd.shake.hint":"Shake the camera or a character","plugin.screenfx.cmd.shake.kind":"Object kind","plugin.screenfx.cmd.shake.label":"Shake","plugin.screenfx.cmd.shake.strength":"Strength","plugin.screenfx.cmd.shake.target":"Target (screen = camera, or a character id)","plugin.screenfx.cmd.trans.color":"Color","plugin.screenfx.cmd.trans.dir":"Direction","plugin.screenfx.cmd.trans.dir.down":"Down","plugin.screenfx.cmd.trans.dir.left":"Left","plugin.screenfx.cmd.trans.dir.right":"Right","plugin.screenfx.cmd.trans.dir.up":"Up","plugin.screenfx.cmd.trans.duration":"Duration (s)","plugin.screenfx.cmd.trans.type":"Style","plugin.screenfx.cmd.trans.type.blinds":"Blinds","plugin.screenfx.cmd.trans.type.circle":"Circle","plugin.screenfx.cmd.trans.type.wipe":"Wipe","plugin.screenfx.cmd.transin.hint":"Reveal the screen with a wipe / circle / blinds","plugin.screenfx.cmd.transin.label":"Transition (reveal)","plugin.screenfx.cmd.transout.hint":"Cover the screen with a wipe / circle / blinds, then change the scene","plugin.screenfx.cmd.transout.label":"Transition (cover)","plugin.screenfx.desc":"Full-screen effects: camera shake, screen flash, and shaped transitions (wipe / circle / blinds). When off, these commands have no effect.","plugin.screenfx.fx.flash.label":"Flash","plugin.screenfx.fx.shake.label":"Shake","plugin.screenfx.fx.transin.label":"Transition (reveal)","plugin.screenfx.fx.transout.label":"Transition (cover)","plugin.screenfx.name":"Full-screen effects"},
    zh: {"plugin.screenfx.cmd.flash.color":"颜色","plugin.screenfx.cmd.flash.duration":"时长(秒)","plugin.screenfx.cmd.flash.hint":"整屏闪一下","plugin.screenfx.cmd.flash.label":"闪光","plugin.screenfx.cmd.shake.duration":"时长(秒)","plugin.screenfx.cmd.shake.hint":"镜头或某个角色震一下","plugin.screenfx.cmd.shake.kind":"对象类型","plugin.screenfx.cmd.shake.label":"震动","plugin.screenfx.cmd.shake.strength":"幅度","plugin.screenfx.cmd.shake.target":"对象（screen＝镜头，或角色id）","plugin.screenfx.cmd.trans.color":"颜色","plugin.screenfx.cmd.trans.dir":"方向","plugin.screenfx.cmd.trans.dir.down":"向下","plugin.screenfx.cmd.trans.dir.left":"向左","plugin.screenfx.cmd.trans.dir.right":"向右","plugin.screenfx.cmd.trans.dir.up":"向上","plugin.screenfx.cmd.trans.duration":"时长(秒)","plugin.screenfx.cmd.trans.type":"样式","plugin.screenfx.cmd.trans.type.blinds":"百叶窗","plugin.screenfx.cmd.trans.type.circle":"圆形","plugin.screenfx.cmd.trans.type.wipe":"擦除","plugin.screenfx.cmd.transin.hint":"用擦除/圆形/百叶窗揭开画面","plugin.screenfx.cmd.transin.label":"转场·揭开","plugin.screenfx.cmd.transout.hint":"用擦除/圆形/百叶窗遮住画面，之后再换场景","plugin.screenfx.cmd.transout.label":"转场·遮住","plugin.screenfx.desc":"整屏特效：镜头震动、画面闪光、转场（擦除/圆形/百叶窗）。关闭后相关指令不再生效。","plugin.screenfx.fx.flash.label":"闪光","plugin.screenfx.fx.shake.label":"震动","plugin.screenfx.fx.transin.label":"转场·揭开","plugin.screenfx.fx.transout.label":"转场·遮住","plugin.screenfx.name":"整屏特效"},
    ja: {"plugin.screenfx.cmd.flash.color":"色","plugin.screenfx.cmd.flash.duration":"長さ(秒)","plugin.screenfx.cmd.flash.hint":"画面全体を一瞬光らせる","plugin.screenfx.cmd.flash.label":"フラッシュ","plugin.screenfx.cmd.shake.duration":"長さ(秒)","plugin.screenfx.cmd.shake.hint":"カメラかキャラを振動させる","plugin.screenfx.cmd.shake.kind":"オブジェクト種別","plugin.screenfx.cmd.shake.label":"振動","plugin.screenfx.cmd.shake.strength":"強さ","plugin.screenfx.cmd.shake.target":"対象（screen＝カメラ、またはキャラid）","plugin.screenfx.cmd.trans.color":"色","plugin.screenfx.cmd.trans.dir":"方向","plugin.screenfx.cmd.trans.dir.down":"下へ","plugin.screenfx.cmd.trans.dir.left":"左へ","plugin.screenfx.cmd.trans.dir.right":"右へ","plugin.screenfx.cmd.trans.dir.up":"上へ","plugin.screenfx.cmd.trans.duration":"長さ(秒)","plugin.screenfx.cmd.trans.type":"スタイル","plugin.screenfx.cmd.trans.type.blinds":"ブラインド","plugin.screenfx.cmd.trans.type.circle":"サークル","plugin.screenfx.cmd.trans.type.wipe":"ワイプ","plugin.screenfx.cmd.transin.hint":"ワイプ／サークル／ブラインドで画面を開く","plugin.screenfx.cmd.transin.label":"転場・開く","plugin.screenfx.cmd.transout.hint":"ワイプ／サークル／ブラインドで画面を覆い、その後シーンを切り替える","plugin.screenfx.cmd.transout.label":"転場・覆う","plugin.screenfx.desc":"全画面エフェクト：カメラの振動、画面のフラッシュ、トランジション（ワイプ／サークル／ブラインド）。オフにすると関連コマンドは無効になります。","plugin.screenfx.fx.flash.label":"フラッシュ","plugin.screenfx.fx.shake.label":"振動","plugin.screenfx.fx.transin.label":"転場・開く","plugin.screenfx.fx.transout.label":"転場・覆う","plugin.screenfx.name":"全画面エフェクト"},
  },
  "spriteanim": {
    en: {"plugin.spriteanim.cmd.hidesprite.fade":"Fade out (s)","plugin.spriteanim.cmd.hidesprite.hint":"Fade the sprite out","plugin.spriteanim.cmd.hidesprite.id":"ID","plugin.spriteanim.cmd.hidesprite.label":"Hide sprite","plugin.spriteanim.cmd.sprite.at":"Position","plugin.spriteanim.cmd.sprite.at.center":"Center","plugin.spriteanim.cmd.sprite.at.left":"Left","plugin.spriteanim.cmd.sprite.at.right":"Right","plugin.spriteanim.cmd.sprite.fade":"Fade in (s)","plugin.spriteanim.cmd.sprite.fps":"FPS","plugin.spriteanim.cmd.sprite.frames":"Frames","plugin.spriteanim.cmd.sprite.height":"Height (%)","plugin.spriteanim.cmd.sprite.hint":"Play a single-row sprite-sheet animation","plugin.spriteanim.cmd.sprite.id":"ID","plugin.spriteanim.cmd.sprite.label":"Play sprite","plugin.spriteanim.cmd.sprite.loop":"Loop","plugin.spriteanim.cmd.sprite.rotation":"Rotation (°)","plugin.spriteanim.cmd.sprite.scale":"Scale","plugin.spriteanim.cmd.sprite.sheet":"Sprite sheet","plugin.spriteanim.cmd.sprite.y":"Vertical position (%)","plugin.spriteanim.desc":"Sprite animation: play a single-row sprite sheet (a frame strip). Disabling stops the related commands.","plugin.spriteanim.kind.sprite":"Sprite","plugin.spriteanim.name":"Sprite animation"},
    zh: {"plugin.spriteanim.cmd.hidesprite.fade":"淡出(秒)","plugin.spriteanim.cmd.hidesprite.hint":"让序列帧淡出消失","plugin.spriteanim.cmd.hidesprite.id":"ID","plugin.spriteanim.cmd.hidesprite.label":"隐藏序列帧","plugin.spriteanim.cmd.sprite.at":"位置","plugin.spriteanim.cmd.sprite.at.center":"中","plugin.spriteanim.cmd.sprite.at.left":"左","plugin.spriteanim.cmd.sprite.at.right":"右","plugin.spriteanim.cmd.sprite.fade":"淡入(秒)","plugin.spriteanim.cmd.sprite.fps":"帧率","plugin.spriteanim.cmd.sprite.frames":"帧数","plugin.spriteanim.cmd.sprite.height":"高度(%)","plugin.spriteanim.cmd.sprite.hint":"播放单行雪碧图动画","plugin.spriteanim.cmd.sprite.id":"ID","plugin.spriteanim.cmd.sprite.label":"播放序列帧","plugin.spriteanim.cmd.sprite.loop":"循环","plugin.spriteanim.cmd.sprite.rotation":"旋转(°)","plugin.spriteanim.cmd.sprite.scale":"缩放","plugin.spriteanim.cmd.sprite.sheet":"雪碧图","plugin.spriteanim.cmd.sprite.y":"垂直位置(%)","plugin.spriteanim.desc":"序列帧动画：播放单行雪碧图（逐帧长条图）。关闭后相关指令不再生效。","plugin.spriteanim.kind.sprite":"序列帧","plugin.spriteanim.name":"序列帧动画"},
    ja: {"plugin.spriteanim.cmd.hidesprite.fade":"フェードアウト(秒)","plugin.spriteanim.cmd.hidesprite.hint":"スプライトをフェードアウト","plugin.spriteanim.cmd.hidesprite.label":"スプライトを隠す","plugin.spriteanim.cmd.sprite.at":"位置","plugin.spriteanim.cmd.sprite.at.center":"中央","plugin.spriteanim.cmd.sprite.at.left":"左","plugin.spriteanim.cmd.sprite.at.right":"右","plugin.spriteanim.cmd.sprite.fade":"フェードイン(秒)","plugin.spriteanim.cmd.sprite.fps":"FPS","plugin.spriteanim.cmd.sprite.frames":"フレーム数","plugin.spriteanim.cmd.sprite.height":"高さ(%)","plugin.spriteanim.cmd.sprite.hint":"横一列のスプライトシートを再生","plugin.spriteanim.cmd.sprite.label":"スプライト再生","plugin.spriteanim.cmd.sprite.loop":"ループ","plugin.spriteanim.cmd.sprite.rotation":"回転(°)","plugin.spriteanim.cmd.sprite.scale":"拡大縮小","plugin.spriteanim.cmd.sprite.sheet":"スプライトシート","plugin.spriteanim.cmd.sprite.y":"垂直位置(%)","plugin.spriteanim.desc":"スプライトアニメ：横一列のスプライトシート（フレーム帯）を再生。オフにすると関連コマンドは動作しません。","plugin.spriteanim.kind.sprite":"スプライト","plugin.spriteanim.name":"スプライトアニメ"},
  },
  "textfx": {
    en: {"plugin.textfx.desc":"Text effects: wave / shaky / rainbow / pop / fade-in ({wave:…} etc. inline in dialogue). When off, these no longer play and text shows normally.","plugin.textfx.name":"Text effects","plugin.textfx.te.fadein.label":"Fade in","plugin.textfx.te.pop.label":"Pop","plugin.textfx.te.rainbow.label":"Rainbow","plugin.textfx.te.shaky.label":"Shake","plugin.textfx.te.wave.label":"Wave"},
    zh: {"plugin.textfx.desc":"文字特效：波浪 / 抖动 / 彩虹 / 弹出 / 淡入（对白里的 {wave:…} 等）。关闭后这些特效不再播放，文字照常显示。","plugin.textfx.name":"文字特效","plugin.textfx.te.fadein.label":"淡入","plugin.textfx.te.pop.label":"弹出","plugin.textfx.te.rainbow.label":"彩虹","plugin.textfx.te.shaky.label":"抖动","plugin.textfx.te.wave.label":"波浪"},
    ja: {"plugin.textfx.desc":"テキスト効果：波／揺れ／虹／ポップ／フェードイン（セリフ内の {wave:…} など）。オフにするとこれらの効果は再生されず、文字は通常表示されます。","plugin.textfx.name":"テキスト効果","plugin.textfx.te.fadein.label":"フェードイン","plugin.textfx.te.pop.label":"ポップ","plugin.textfx.te.rainbow.label":"レインボー","plugin.textfx.te.shaky.label":"シェイク","plugin.textfx.te.wave.label":"ウェーブ"},
  },
  "voicefx": {
    en: {"plugin.voicefx.cfg.enabled":"Typing blips","plugin.voicefx.cfg.level":"Blip level","plugin.voicefx.cfg.wobble":"Pitch wobble","plugin.voicefx.desc":"Synthesized voice: makes a speaking sound at each actor pitch while typing (a fallback when no per-line voice is recorded). When off, typing is silent.","plugin.voicefx.field.voice":"Blip pitch (Hz)","plugin.voicefx.name":"Synthesized voice"},
    zh: {"plugin.voicefx.cfg.enabled":"打字音","plugin.voicefx.cfg.level":"打字音音量","plugin.voicefx.cfg.wobble":"音高抖动","plugin.voicefx.desc":"合成配音：打字时按角色音调发出“说话声”（没有逐句真人配音时的兜底）。关闭后打字静音。","plugin.voicefx.field.voice":"打字音音高（Hz）","plugin.voicefx.name":"合成配音"},
    ja: {"plugin.voicefx.cfg.enabled":"タイピング音","plugin.voicefx.cfg.level":"タイピング音の音量","plugin.voicefx.cfg.wobble":"音程の揺れ","plugin.voicefx.desc":"合成ボイス：タイプ中にキャラクターの音程で「話し声」を鳴らします（セリフごとの実音声がない場合の代替）。オフにするとタイプ音は無音になります。","plugin.voicefx.field.voice":"ブリップ音の高さ（Hz）","plugin.voicefx.name":"合成ボイス"},
  },
  "voicerecord": {
    en: {"plugin.voicerecord.desc":"Per-line voice authoring: the Voice button on spoken lines records or imports a clip and tunes its start offset. Turning it off only hides the authoring UI — already-attached voice keeps playing.","plugin.voicerecord.name":"Voice recording"},
    zh: {"plugin.voicerecord.desc":"逐句配音编辑：台词行的「配音」按钮，可录音或导入音频并调整起始修正。关闭只隐藏编辑入口——已配好的配音照常播放。","plugin.voicerecord.name":"配音录制"},
    ja: {"plugin.voicerecord.desc":"セリフごとのボイス編集：セリフ行の「ボイス」ボタンで録音・読み込み・開始補正の調整ができます。オフにすると編集入口が消えるだけで、設定済みのボイスは再生されます。","plugin.voicerecord.name":"ボイス収録"},
  },
}
